### ISSUE TITLE
Not working with Windows 11 in VM

### ISSUE THREAD

**Issue by Upgrad3** [shellster/HideVBoxTray#1]
First of all, id like to say thank you for this.

I tried this in a VM running Windows 11 22H2. Process VBoxTray.exe simply does not start and launching manually shows an error (see screenshot)
![1](https://user-images.githubusercontent.com/16259892/212501919-75c0229d-5fe3-4f7b-8a68-822831f8e156.png)

**Comment by shellster** [comment]
Thanks for reporting this.  PR's are welcome.  I haven't used this in awhile and Windows 11 changed things a fair bit as far as the tray and such.  That said, the error message is pretty straightforward.  You probably just need to figure out where VBoxTray.exe is running from and update and recompile.

**Comment by Upgrad3** [comment]
Thanks for the reply, It is in System32, i have tried moving it editing the reg key, and renaming things all to no avail.

**Comment by shellster** [comment]
I think you need to double check your work.  I finally got a chance to try a Windows 11 VM and it worked just fine.  You should double check the location in the .reg file before you install it.  By default it is C:\mykit.   You can change that if you like, you you need to update the .reg file and run it.  Then reboot.
